# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7892f45aac02429f09aaec57e20e717e99a21f63f04c620fa5c26cd570c532543d69afc896f0c47e0c236ac45f8c380b2510df611b7c9e30b5aaed7bd29e3f5

test:
  secret_key_base: 65f0faac03b4f7a67944cfdb023bb1375cd154c84dae73758046a366ac7fc06d780a9aeeffadbab0a96dfdcdef864a7171a1d3918d5be65f783b464c8a0c7a69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
